language: c

os:
  - linux
  - osx

dist: focal
osx_image: xcode12.2

# Temporary until #2 is fixed.
jobs:
  allow_failures:
    - os: osx

compiler:
  - gcc
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install s-lang ; fi

addons:
  apt:
    update: true
    packages:
    - chrpath
    - libcanlock-dev
    - libslang2-dev
    - libssl-dev
    - libuu-dev

# No 'make test' yet
script: ./configure && make